### ISSUE TITLE
Kubernetes Dashboard版本升级详解 - jimmysong.io

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#102]
https://jimmysong.io/posts/kubernetes-dashboard-upgrade/

**Comment by dangzhiqiang** [comment]
我是用kubeadm搭建的v1.6版本，咨询一下，普通用户只用token可以登陆dashboard吗，如果可以，请问如何生成普通用户的token？谢谢。

**Comment by dangzhiqiang** [comment]
我的意思是，能不能像创建admin用户一样创建普通用户，然后用生成的token登陆，这样就不用改API参数，这样感觉更方便一些。

**Comment by rootsongjc** [comment]
@dangzhiqiang  dashboard支持使用token和证书登陆两种方式，不过证书里面页需要配置token的，页就是说token是必不可少的。本文中已经说明了如何生成token，请参考“例如为brand用户生成token”。另外，可以可以加入kubernetes的微信群方便提问。https://jimmysong.io/about

**Comment by johnzheng1975** [comment]
赞，难得有这么详细的。试验之前先赞一下。

**Comment by rootsongjc** [comment]
@johnzheng1975 🙏 请多指教

**Comment by johnzheng1975** [comment]
实验成功，很好！

**Comment by rootsongjc** [comment]
@johnzheng1975 You're welcome.

**Comment by hassanyang** [comment]
先版本v1.9 + dashboard V1.8.1 kubectl 中获取的token不需要base64 解码了吧。
我自己安装官方教程，使用kubeadm搭建的1.9版本，从https://github.com/kubernetes/dashboard安装的v1.8.1。 登陆时选token，填入的是kubectl中输出的token，登陆成功。

**Comment by rootsongjc** [comment]
@hassanyang 如果是使用`kubectl describe secret`来查看的token，实际上已经经过base64解码了，至于v1.9的dashboard到底是需不需要经过base64解码的token我还没有验证过。

**Comment by chenvista** [comment]
$ kubectl -n kube-system get svc kubernetes-dashboard
NAME                   TYPE       CLUSTER-IP        EXTERNAL-IP   PORT(S)        AGE
kubernetes-dashboard   NodePort   169.169.135.182   <none>        443:8013/TCP   17m


然后死活找不到8013这个端口

**Comment by chenvista** [comment]
我是用的1.9加 dashboard V1.8.0   dashboard.yaml是从下载的推荐配置，只在最后type: NodePort
