### ISSUE TITLE
pod中hosts问题

### ISSUE THREAD

**Issue by heshengkai** [rootsongjc/rootsongjc.github.io#106]
@rootsongjc 请问一下，我现在有这样一个需求，不知道如何去实现，需要请教您。我在创建pod时,在hosts文件里需要生成hostname和127.0.0.1对应。
现pod中hosts文件生成如下：
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.30.68.3	icp-service-platform-723533465-m8npf
```
我需要将127.0.0.1  icp-service-platform-723533465-m8npf也能对应起来。

**Comment by rootsongjc** [comment]
不知你的这种需求是向达成什么目录？为何不使用DNS来解析？如果你一定要这样做的话，可以使用以下两种方式实现：
- 对于kubernetes1.7及以上版本，清参考[使用 HostAliases 向 Pod /etc/hosts 文件添加条目](https://k8smeetup.github.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/)
- 其它版本可以在容器启动的时候通过initContainer来实现，通过脚本来修该文件

**Comment by heshengkai** [comment]
我现在使用的版本是1.6的。这个是程序里需要这个需求，我现在把原有的程序迁移到k8s上，报无法解析的错误，导致无法向zookeeper中注册服务。
这个是我们原有程序所在的服务器的hosts中文件的内容：127.0.0.1	host-192-168-1-15 localhost

请问具体如何通过initContainer来实现。

**Comment by rootsongjc** [comment]
这种情况下你应该使用 [StatefulSet](https://jimmysong.io/kubernetes-handbook/concepts/statefulset.html) 这种资源类型，它可以保证 pod 拥有稳定的网络和主机标志。

**Comment by heshengkai** [comment]
好的，忘记这茬了，这种无状态服务，习惯用deployment了，我用StatefulSet来试试，谢谢宋老师，你的blog太棒了，让我受益匪浅，由衷的感谢您。
