### ISSUE TITLE
随时随地访问您的Kubernetes集群 - jimmysong.io|宋净超的博客|Cloud Native|Big Data

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#114]
https://jimmysong.io/posts/kubernetes-anytime-anywhere/

**Comment by imroc** [comment]
cool

**Comment by zhoulouzi** [comment]
牛逼了

**Comment by bryanleekw** [comment]
Cool... similar to all cloud providers, such as GCP, AWS, Azure etc, which has provides web apps to access cloud console

**Comment by rootsongjc** [comment]
@bryanleekw Exactly! You can develop an app by yourself, just use kubernetes API.

**Comment by bryanleekw** [comment]
HI Song, Sure! your repository is so rich! I need to learn a lot from you on how to build kubernetes!

**Comment by rootsongjc** [comment]
@bryanleekw Thanks. Glad to contact with you. https://jimmysong.io/about
