### ISSUE TITLE
Istio 中的 Sidecar 注入及透明流量劫持过程详解

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#139]
https://jimmysong.io/blog/sidecar-injection-iptables-and-traffic-routing/ 

 本文基于 Istio 1.5.1 版本，介绍了 sidecar 模式及其优势 sidecar 注入到数据平面，如何做流量劫持和转发的，以及流量是怎样路由到 upstream 的。

**Comment by wubo0067** [comment]
请问，在istio 1.7版本就看不到流量劫持的iptables信息呢

**Comment by rootsongjc** [comment]
> @wubo0067
> 请问，在istio 1.7版本就看不到流量劫持的iptables信息呢

我还没在 Istio 1.7 下测试过，等我再看下。

**Comment by Ruil1n** [comment]
关于文中Istio sidecar流量劫持示意图，对于序号15-16的流程（ ISTIO_OUTPUT -> ISTIO_REDIRECT ->  POSTROUTING）有一些疑惑。其是否不应该进入ISTIO_REDIRECT链（即直接连接POSTROUTING链）？因为规则中ISTIO_REDIRECT链只有一个转发流量到Envoy的规则，并不能从此处流转到POSTROUTING链。同时最后流量是来自istio-proxy用户空间，所以这里的流程是否应该是 ISTIO_OUTPUT -> POSTROUTING

**Comment by ElwinGao4444** [comment]
感觉流量劫持示意图里的步骤15和16是不是画错了？
从ISTIO_OUTPUT出来，应该直接回到POSTROUTING去了吧？到了ISTIO_REDERECT应该就没有机会直接转到POSTROUTING了。

**Comment by mtccvip** [comment]
1.sidecar劫持所有进出pod的流量，那么直接访问pod ip或者svc ip流量还是会经过enovy，这个时候访问流量是不受任何影响的吗

**Comment by mtccvip** [comment]
2.virtual service中的hosts项没有配置service name，但是访问service name还是能通，这个是为啥

**Comment by mtccvip** [comment]
3.未开启sidecar的pod去访问开启sidecar的pod会有什么限制？

**Comment by rootsongjc** [comment]
> @Ruil1n
> 关于文中Istio sidecar流量劫持示意图，对于序号15-16的流程（ ISTIO_OUTPUT -> ISTIO_REDIRECT ->  POSTROUTING）有一些疑惑。其是否不应该进入ISTIO_REDIRECT链（即直接连接POSTROUTING链）？因为规则中ISTIO_REDIRECT链只有一个转发流量到Envoy的规则，并不能从此处流转到POSTROUTING链。同时最后流量是来自istio-proxy用户空间，所以这里的流程是否应该是 ISTIO_OUTPUT -> POSTROUTING 

根据你今天在「云原生社区 Istio SIG」中的回复，我更新了下 Istio 中流量劫持详解的图片。

**Comment by rootsongjc** [comment]
> @mtccvip
> 1.sidecar劫持所有进出pod的流量，那么直接访问pod ip或者svc ip流量还是会经过enovy，这个时候访问流量是不受任何影响的吗

流量接触对于应用来说是透明的（无感知），没有影响。

**Comment by glyslxq** [comment]
宋老师，近期使用istio1.6遇到个比较奇怪的问题，一个k8s集群中，同一命名空间下的pod，注入了sidecar的pod无法访问未注sidecar的pod的 mysql 和 redis服务，但是访问这些服务的监控指标端口又没问题，pod在不同命名空间的话没有这个问题，有点懵

**Comment by glyslxq** [comment]
> 宋老师，近期使用istio1.6遇到个比较奇怪的问题，一个k8s集群中，同一命名空间下的pod，注入了sidecar的pod无法访问未注sidecar的pod的 mysql 和 redis服务，但是访问pod的监控指标端口又没问题，pod在不同命名空间的话没有这个问题，有点懵

发现不是命名空间的原因
A 是注入了sidecar的pod 
B 是redis pod，未注入sidecar
C 是问题主机
D 是正常主机

1.删掉B，新创建B放在C上，A不重启，无论A部署在C还是D，都可以正常访问，A重启后就无法访问
2.删掉B，新创建B放在D上，无论A是否重启，都能正常访问

检查了k8s和iptables，并没有发现有什么不同
抓包分析，握手成功后，A就马上主动发起结束对话，中间有一个TLSv1的client hello报文，打算先看看istio安全这块

**Comment by zengqi826** [comment]
宋老师，如果用自研的网关来替换envoy，该如何操作呢

**Comment by rootsongjc** [comment]
> @zengqi826
> 宋老师，如果用自研的网关来替换envoy，该如何操作呢。
> 是否就和mson一样，修改代理镜像就可以？https://mosn.io/docs/quick-start/istio/

你指的是用自己的 proxy 来替换 Istio 中默认的 Envoy sidecar proxy 吧，只要你们的代理兼容 xDS 协议就是可以的。

**Comment by zengqi826** [comment]
> > @zengqi826
> > 宋老师，如果用自研的网关来替换envoy，该如何操作呢。
> > 是否就和mson一样，修改代理镜像就可以？https://mosn.io/docs/quick-start/istio/
> 
> 你指的是用自己的 proxy 来替换 Istio 中默认的 Envoy sidecar proxy 吧，只要你们的代理兼容 xDS 协议就是可以的。

是的，用自研的网关作为sidecar proxy。因为envoy看起来就像一个网关

**Comment by yuchunyun** [comment]
我使用istio 1.13版本。想看下inbound的流程，然后通过istioctl pc listeners customers-v1-6d8df67d9f-g6nsf --port 15006 -o json 查看到访问这个容器3000端口，被转到了route:"inbound|3000||"-->"cluster": "inbound|3000||"，但想查看cluster->endpoint时使用istioctl pc endpoints customers-v1-6d8df67d9f-g6nsf --cluster="inbound|3000||"  -o json返回确是空的，执行istioctl pc clusters customers-v1-6d8df67d9f-g6nsf  --direction inbound  -o json 也看不到是如何转到应用pod的3000端口的。所以想请教一下新版本的istio inbound流程是不是有什么变化啊？

**Comment by rootsongjc** [comment]
> @yuchunyun
> 我使用istio 1.13版本。想看下inbound的流程，然后通过istioctl pc listeners customers-v1-6d8df67d9f-g6nsf --port 15006 -o json 查看到访问这个容器3000端口，被转到了route:"inbound|3000||"-->"cluster": "inbound|3000||"，但想查看cluster->endpoint时使用istioctl pc endpoints customers-v1-6d8df67d9f-g6nsf --cluster="inbound|3000||"  -o json返回确是空的，执行istioctl pc clusters customers-v1-6d8df67d9f-g6nsf  --direction inbound  -o json 也看不到是如何转到应用pod的3000端口的。所以想请教一下新版本的istio inbound流程是不是有什么变化啊？

最近几天更新了下这篇博客，根据当时 Istio 1.13 版本更新了文章的部分内容，并重新排版，增加更新说明。

**Comment by mark8s** [comment]
给力！刚好在研究这一块~
