### ISSUE TITLE
Service Mesh—— 后 Kubernetes 时代的微服务

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#141]
https://jimmysong.io/blog/service-mesh-the-microservices-in-post-kubernetes-era/ 

 本文是以前所写内容的重新修订并收录于 ServiceMesher 社区的 Istio Handbook 中，其他章节仍在编纂中。

**Comment by JinlongWukong** [comment]
写的太好了

**Comment by rootsongjc** [comment]
> @SzHeJason
> 发现宝藏啊 够我学习几个月了 感谢感谢

谢谢，Istio Handbook 实体书也快出版了。

**Comment by SzHeJason** [comment]
一定支持！！！

**Comment by oneslideicywater** [comment]
加油加油
