### ISSUE TITLE
Sidecar injection and transparent traffic hijacking process in Istio explained in detail

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#163]
https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/ 

 Based on Istio version 1.5.1, this blog describes the sidecar pattern and its advantages. How sidecar be injected into the data plane, how traffic hijacking and forwarding is done, and how traffic is routed to upstream.

**Comment by MaciekLeks** [comment]
Amazing job. One silly question since I'm not iptables master or even a regular user. In "iptables manipulation analysis" you perfectly shows in the diagram ingess/egress route via nat table. 8th arrow enters the reviews container and then the response (to productpage goes out via  outbout route (starting with 9th arrow)?

**Comment by rootsongjc** [comment]
> @MaciekLeks
> Amazing job. One silly question since I'm not iptables master or even a regular user. In "iptables manipulation analysis" you perfectly shows in the diagram ingess/egress route via nat table [(diagram).](https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/envoy-sidecar-traffic-interception-jimmysong-blog-en-20210407.png) 8th arrow enters the reviews container and then the response to productpage goes out via  outbout route (starting with 9th arrow)?:/ I don't think so, but the arrow numbering suggests this flow.

I would like to know your opinion on how the traffic goes from sidecar into the app container?

**Comment by MaciekLeks** [comment]
I slept with it and now I think the response comes out with 9th arrow, so it means that `istio-proxy` comes to play twice for each request (request on 15006, response on 15001). Am I right?

**Comment by MaciekLeks** [comment]
> > @MaciekLeks
> > Amazing job. One silly question since I'm not iptables master or even a regular user. In "iptables manipulation analysis" you perfectly shows in the diagram ingess/egress route via nat table [(diagram).](https://jimmysong.io/en/blog/sidecar-injection-iptables-and-traffic-routing/envoy-sidecar-traffic-interception-jimmysong-blog-en-20210407.png) 8th arrow enters the reviews container and then the response to productpage goes out via  outbout route (starting with 9th arrow)?:/ I don't think so, but the arrow numbering suggests this flow.
> 
> I would like to know your opinion on how the traffic goes from sidecar into the app container?

I slept with it and now I think the response comes out with 9th arrow, so it means that istio-proxy comes to play twice for each request (request on 15006, response on 15001). Am I right?

**Comment by MaciekLeks** [comment]
I'm coming back again here :) I have doubts according to *Understand Inbound Handler* section. Please have a look at [A virtual listener on the pod IP for each exposed port for inbound traffic](https://discuss.istio.io/t/a-virtual-listener-on-the-pod-ip-for-each-exposed-port-for-inbound-traffic/11046). So, the yielded listener list should not contain the line `172.17.0.15        9080      HTTP` (only if the IP address is the reviews pod IP address which is unclear in your text).

**Comment by rootsongjc** [comment]
> @MaciekLeks
> I'm coming back again here :) I have doubts according to *Understand Inbound Handler* section. Please have a look at [A virtual listener on the pod IP for each exposed port for inbound traffic](https://discuss.istio.io/t/a-virtual-listener-on-the-pod-ip-for-each-exposed-port-for-inbound-traffic/11046). So, the yielded listener list should not contain the line `172.17.0.15        9080      HTTP` (only if the IP address is the reviews pod IP address which is unclear in your text).

`172.17.0.15` it's the IP address of `reviews` pod.  That listener is supposed to be there and has nothing to do with Istio.
