### ISSUE TITLE
新的开始——告别蚂蚁，加入 Tetrate

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#170]
https://jimmysong.io/blog/moving-on-from-ant-group/ 

 今天是我在蚂蚁的最后一天，明天我就要在 Tetrate 开始新的学期了。

**Comment by metadeng** [comment]
明天更美好

**Comment by pflong** [comment]
未来越来越棒~

**Comment by rootsongjc** [comment]
> @metadeng
> 明天更美好

谢谢你的祝福。

**Comment by zhangguanzhang** [comment]
我也差不多明天离职😄

**Comment by rootsongjc** [comment]
> @zhangguanzhang
> 我也差不多明天离职😄

好巧啊

**Comment by Alibner** [comment]
越来越好

**Comment by Alibner** [comment]
> @zhangguanzhang
> 我也差不多明天离职😄

馆长起飞，越来越牛逼

**Comment by willseeyou** [comment]
期待带来更多更好的技术

**Comment by biruce** [comment]
加入了创业公司，有没有创业的感觉？:smile:

**Comment by rootsongjc** [comment]
> @biruce
> 加入了创业公司，有没有创业的感觉？:smile:

不知道何为“创业的感觉”？

**Comment by biruce** [comment]
> > @biruce
> > 加入了创业公司，有没有创业的感觉？smile
> 
> 不知道何为“创业的感觉”？

当老板的感觉 smile

**Comment by biruce** [comment]
> > @biruce
> > 加入了创业公司，有没有创业的感觉？smile
> 
> 不知道何为“创业的感觉”？

当老板的感觉 :smile

**Comment by biruce** [comment]
> > @biruce
> > 加入了创业公司，有没有创业的感觉？smile
> 
> 不知道何为“创业的感觉”？

当老板的感觉 :smile:

**Comment by rootsongjc** [comment]
> @biruce
> > > @biruce
> > > 加入了创业公司，有没有创业的感觉？smile
> > 
> > 不知道何为“创业的感觉”？
> 
> 当老板的感觉 :smile:

Are you kidding me? 不当孙子就不错了，还老板呢

**Comment by biruce** [comment]
> > @biruce
> > > > @biruce
> > > > 加入了创业公司，有没有创业的感觉？smile
> > > 
> > > 
> > > 不知道何为“创业的感觉”？
> > 
> > 
> > 当老板的感觉 smile
> 
> Are you kidding me? 不当孙子就不错了，还老板呢

:smile:
