### ISSUE TITLE
云原生初学者必读

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#179]
https://jimmysong.io/blog/must-read-for-cloud-native-beginner/ 

 这篇文章将助于各位有志于从事云原生领域工作或需要了解该领域背景的人群快速入门 Kubernetes 和云原生。

**Comment by HellMagic** [comment]
你好，上面的链接： [云原生知识图谱](https://github.com/cloudnativeto/cloudnative-knowledge-map) 项目链接无效，404。

**Comment by rootsongjc** [comment]
> @HellMagic
> 你好，上面的链接： [云原生知识图谱](https://github.com/cloudnativeto/cloudnative-knowledge-map) 项目链接无效，404。

这个项目暂时是私有仓库，因为还在准备期，所以没放出来，我在原文中把这个链接去掉吧。

**Comment by HellMagic** [comment]
> @rootsongjc
> > @HellMagic
> > 你好，上面的链接： [云原生知识图谱](https://github.com/cloudnativeto/cloudnative-knowledge-map) 项目链接无效，404。
> 
> 这个项目暂时是私有仓库，因为还在准备期，所以没放出来，我在原文中把这个链接去掉吧。

好的，期待学习下~
