### ISSUE TITLE
理解 Istio Service Mesh 中 Envoy 代理 Sidecar 注入及流量劫持

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#183]
https://jimmysong.io/blog/envoy-sidecar-injection-in-istio-service-mesh-deep-dive/ 

 以往有很多文章讲解 Istio 是如何做 Sidecar 注入的，但是没有讲解注入之后 Sidecar 工作的细节。本文将带大家详细了解 Istio 是如何将 Envoy 作为 Sidecar 的方式注入到应用程序 Pod 中，及 Sidecar 是如何做劫持流量的。

**Comment by lklkxcxc** [comment]
ISTIO_IN_REDIRECT 不是导向到15001但是上面流量劫持示意图是15006端口，是为什么

**Comment by rootsongjc** [comment]
> @lklkxcxc
> ISTIO_IN_REDIRECT 不是导向到15001但是上面流量劫持示意图是15006端口，是为什么

这里是笔误，感谢你指出这个问题。原文中那里应该是 ISTIO_IN_REDIRECT 是导向到 inbound 的 15006 端口，因为最开始写这篇文章的时候很早，在 Istio 较早的版本中（具体哪个版本我还没法确定，但是一开始写作本文时 Istio 1.1 版本还没发布，1.1 是 2019-03-19 发布的，本文是 2018 年 9 月 11 日完成的，后来经过很多次更新，原文中这个错误忘记更新了），Istio 采用同一个 VirtualListener 在端口 15001 上同时处理入向和出向的请求。 该方案存在一些潜在的问题，例如可能会导致出现死循环。在 1.4 版本之后，Istio 为 Envoy 单独创建了一个 VirtualInboundListener，在 15006 端口监听入向请求，原来的 15001 端口只用 于处理出向请求。

关于该路由规则的设置可以很清楚的在 `istio-init` 容器的启动日志中看到。
```
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
```

原文已修改正确。
