### ISSUE TITLE
使用 EKS-D 和 Istio 保证混合云环境一致性

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#188]
https://jimmysong.io/blog/eks-eksd-istio-hybrid-cloud/ 

 本文将为你解析 EKS-D 的战略意义，说明它是如何与 Istio 共同保证混合云环境一致性的。

**Comment by TedCat** [comment]
个人感觉，跨云商的网络稳定性 和 网络费用 会是两个很高的坎，对于大流量应用好像很难用这种模式进行部署

**Comment by rootsongjc** [comment]
> @TedCat
> 个人感觉，跨云商的网络稳定性 和 网络费用 会是两个很高的坎，对于大流量应用好像很难用这种模式进行部署

你说的没错，虽然技术上可行，但还需要结合成本考量。
