### ISSUE TITLE
Why You Should Choose NGAC as Your Access Control Model

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#207]
https://jimmysong.io/en/blog/why-you-should-choose-ngac-as-your-access-control-model/ 

 This article will introduce you to the next generation permission control model, NGAC, and compare ABAC, RABC, and explain why you should choose NGAC.

**Comment by mmailaender** [comment]
Thank you for sharing these interesting thoughts! Do you know about some identity provider that are already implementing this approach, or do I have to develop this as a custom solution?

**Comment by rootsongjc** [comment]
> @mmailaender
> Thank you for sharing these interesting thoughts! Do you know about some identity provider/libraries that are already implementing this approach, or do I have to develop this as a custom solution?

As far as I know, there are open source projects on GitHub(for example https://github.com/PM-Master/Harmonia-1.5 ) that implement NGAC, and Tetrate's product [TSB](https://www.tetrate.io/tetrate-service-bridge/) also implements NGAC.
