### ISSUE TITLE
Istio Service Mesh官方文档中文版 - jimmysong.io

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#21]
https://jimmysong.io/posts/istio-service-mesh-doc-zh/

**Comment by bamaao** [comment]
楼主，问一个问题。

我部署istio，然后用istio部署grpc服务端和客户端，我客户端不能访问istio。
总是报错：
io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
invalid content-type: null
trailers: Metadata(:status=404,date=Tue, 07 Nov 2017 09:57:48 GMT,server=envoy)


但是我通过NodePort的方式或者通过istio ingress配置的方式都能访问。

请问我还需要配置什么吗？我gRpc是java gRpc实现的。

**Comment by bamaao** [comment]
gRpc服务端部署的时候不需要istio kube-inject吗？

**Comment by rootsongjc** [comment]
@bamaao 你好，建议你到[serivce mesh中文网](http://www.servicemesh.cn/)提问，我还没试过直接访问istio的情况，我是直接使用traefik ingress。

**Comment by bamaao** [comment]
谢谢。

我是istio上部署grpc服务端和grpc客户端，通过istio ingress暴露grpc客户端给外部访问，现在我能访问暴露的grpc客户端，但是grpc客户端不能访问grpc服务端，grpc是基于java grpc。
