### ISSUE TITLE
新疆北疆房车自驾之旅 · Jimmy Song

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#234]
https://jimmysong.io/blog/xinjiang-trip/ 

 记录我与 Addo 一行七天的房车自驾之旅。

**Comment by llaoj** [comment]
也想去一趟感受一下

**Comment by rootsongjc** [comment]
> @llaoj
> 也想去一趟感受一下

去吧，强烈推荐。

**Comment by huanlekenan** [comment]
你有感受到新疆对涉疫地区游客的遣返吗？7.31我在赛湖回乌鲁木齐路上就各种检测了。

**Comment by rootsongjc** [comment]
> @huanlekenan
> 你有感受到新疆对涉疫地区游客的遣返吗？7.31我在赛湖回乌鲁木齐路上就各种检测了。

我当时只有收到新疆本地的防疫部门打来的电话询问我未知，并没有通知我们返程或者离开新疆。

**Comment by snappyJack** [comment]
相当不错呀!

**Comment by rootsongjc** [comment]
> @snappyJack
> 相当不错呀!

是的，国庆节期间去也可以的

**Comment by DKCopy** [comment]
7天时间有点赶哦 
琼库什台不错 我去的那次可惜天气不好 不过也额外壮观
新疆值得多去几次

**Comment by rootsongjc** [comment]
> @DKCopy
> 7天时间有点赶哦 
> 琼库什台不错 我去的那次可惜天气不好 不过也额外壮观
> 新疆值得多去几次

是的，离开伊犁的时候我还有些恋恋不舍，以后希望再去。
