### ISSUE TITLE
Vagrant介绍-从使用到放弃完全指南 - jimmysong.io

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#43]
https://jimmysong.io/posts/vagrant-intro/

**Comment by Lupeipei** [comment]
楼主，篇幅不完整，请问放弃篇在哪？另，添加box，也可以vagrant init ubuntu/trusty64

**Comment by rootsongjc** [comment]
@Lupeipei 关于Vagrant我一共就写了这一篇文章，然后就放弃继续使用了，当时主要是想用它来部署一套Contiv开发测试环境，后来直接使用物理机来测试，就没继续再搞Vagrant了。

**Comment by Lupeipei** [comment]
@rootsongjc 小白一枚，刚开始用Vagrant，并不了解，搜到了您的文章，看到放弃，猜想vagrant可能在某些场景下并不适用，所以好奇放弃篇是什么内容，谢谢楼主的回复和分享！

**Comment by rootsongjc** [comment]
@Lupeipei 其实这个就是放弃篇😄 《Vagrant从还没入门就放弃完全指南》
