### ISSUE TITLE
使用gitment为你的网站添加评论框 - jimmysong.io

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#66]
https://jimmysong.io/posts/creating-comment-box-with-gitment/

**Comment by fbigun** [comment]
真的可以用啊

# 是真的

**Comment by rootsongjc** [comment]
@fbigun 当然可以用，但是我可以改你的评论，😄

**Comment by fbigun** [comment]
@rootsongjc   :confused:
