### ISSUE TITLE
使用Helm管理kubernetes原生应用 - jimmysong.io

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/rootsongjc.github.io#98]
https://jimmysong.io/posts/manage-kubernetes-native-app-with-helm/

**Comment by heshengkai** [comment]
请教一下，创建了chart后，部署应用。release的名称是如何生成的？

**Comment by rootsongjc** [comment]
@heshenkai 如果直接用helm命令部署的时候不指定name，那么release的名字是在两个随机单词加chart名字组成，例如laughing-alex-mychart，也可以在使用`helm install`部署的时候用`-n`来指定realease名字。

**Comment by heshengkai** [comment]
好的，了解了。谢谢宋老师。
